### ISSUE TITLE
Trouver une meilleure manière de récupérer les utilisateurs

### ISSUE THREAD

**Issue by Teyk0o** [Teyk0o/wwsnb#5]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez.**
Actuellement, pour suggérer les utilisateurs lors d'un @, on récupère les utilisateurs affichés à gauche + on met en cache les utilisateurs qui parlent dans le tchat, ça peut causer quelques ralentissements, je pense, du moins ce n'est pas optimal.

**Décrivez la solution que vous souhaitez**
Je n'ai pas encore de solution à proposer, mais la problématique à résoudre est : Comment accéder à des éléments existants, mais non dessiné sur le HTML dû à l'utilisation de React_Virtualized par BBB.

**Comment by Mimouss56** [comment]
Je pense que juste la colonne de gauche avec un localStorage
 
 Je suis en train de travailler dessus pour la version ts

**Comment by Teyk0o** [comment]
Non justement, on ne peut pas utiliser juste la colonne de gauche, car les utilisateurs ne sont pas draw donc impossible de les récupérer comme ça.
ça aurait été si simple que ça, je l'aurais déjà fait comme ça :)

Voici un exemple dynamique de comment fonctionne React_Virtualized :
https://bvaughn.github.io/react-virtualized/#/components/List
Tu verras que les éléments non visibles à l'écran n'existent pas, donc ne sont pas récupérables si facilement.

**Comment by Teyk0o** [comment]
Finalement ça fonctionne parfaitement comme ça, donc inutile de modifier ce qui fonctionne
