### ISSUE TITLE
Implémenter un auto-updater

### ISSUE THREAD

**Issue by Teyk0o** [Teyk0o/wwsnb#6]
**Votre demande de fonctionnalité est-elle liée à un problème ? Décrivez.**
Pour éviter aux utilisateurs de devoir télécharger et réinstaller l'extension à chaque mise à jour, il faut trouver un moyen d'auto-update l'extension.

**Décrivez la solution que vous souhaitez**
Mettre les fichiers de l'extension sur le FPT du site web et dire à l'extension de check si une update est disponible à chaque lancement, si oui, l'installer silencieusement.
C'est important que les utilisateurs n'aient rien à faire.

**Comment by Teyk0o** [comment]
@Mimouss56 je pense que c'est une des premières choses à faire, tu en penses quoi ? Il faut réfléchir comment faire pour ne pas envoyer des requêtes réseaux pour rien, etc...

**Comment by Mimouss56** [comment]
Juste un handleCheck version au lancement de Firefox.

**Comment by Teyk0o** [comment]
#16
